DROP DATABASE IF EXISTS bamazon;
CREATE DATABASE bamazon;
USE bamazon;

CREATE TABLE products(
id INTEGER(11) AUTO_INCREMENT,
product_name VARCHAR(50) NOT NULL,
department_name VARCHAR(50) NOT NULL,
price NUMERIC(4, 2) NOT NULL,
stock_quantity NUMERIC(11) NOT NULL,
PRIMARY KEY(id)
);